### ISSUE TITLE
Error when running airsenal_update_db

### ISSUE THREAD

**Issue by mazhar-debug** [alan-turing-institute/AIrsenal#226]
Matches and player-scores already up-to-date
Checking team
Traceback (most recent call last):
  File "/home/user/.local/bin/airsenal_update_db", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.7/site-packages/airsenal/scripts/update_results_transactions_db.py", line 67, in main
    db_players = sorted(get_current_players(season=season, dbsession=session))
  File "/home/user/.local/lib/python3.7/site-packages/airsenal/framework/utils.py", line 193, in get_current_players
    assert len(current_players) == 15
AssertionError

It's not able to pick up my team. I set it initially, and then switched players. I've also tried setting a team with another team-id and not make any trades, and I still get this error.

I'm running this on an Ubuntu Azure VM, with no Anaconda (as mentioned in a previous issue).

**Comment by jack89roberts** [comment]
Hi @mazhar-debug , this bug is because we can't get your squad from the API before the season has started (basically, your team isn't defined before GW1). We should fix the error message but it will not stop you from running predictions or generating a team - you should be able to run `airsenal_run_prediction` and `airsenal_make_team` normally (to generate a full squad, the `airsenal_run_optimization` that's normally run also won't work until after the season has started).


(this is the same as #219)

**Comment by mazhar-debug** [comment]
Ahh, that makes sense! Thank you for the quick reply.

I'm really looking forward to entering my beepbop-computer-controlled team to my offices league this year!

Thanks a lot for all the work that you guys are doing!
