### ISSUE TITLE
Change FPL Team ID without having to recreate the database

### ISSUE THREAD

**Issue by Hughesy** [alan-turing-institute/AIrsenal#253]
When I try to change the FPL ID to a different one, it cannot pull through the new squad. It always seems to pull though the previous team. I have updated the FPL_TEAM_ID file, with the new ID, and ran `airsenal_run_pipeline`. Where else would store the previous squad?

**Comment by jack89roberts** [comment]
This is likely to be #77 again where it's not picking up new values in the file after installation. If you'd like to regularly play with different IDs etc. the best thing is probably to (re)install AIrsenal in editable mode. From the AIrsenal directory and with the airsenalenv conda environment activated:
```
pip install --upgrade --force-reinstall -e .
```
After that, it should pick up any changes to the FPL_TEAM_ID file (or any other AIrsenal code file) automatically.

If you re-ran the whole pipeline this won't be a problem but your squad is also stored in the database (which is deleted and recreated as part of the pipeline command), so that database table also needs to be cleared to use a new team ID correctly. We should add a way to run it with multiple teams without having to delete and recreate everything. I'll change the title of this issue to be about adding that feature, assuming the change above fixes your problem.

**Comment by Hughesy** [comment]
I'll give it a try now. 

Is it possible to not store the squad in the Database? It seems counterproductive to re-run the predictions for each fpl team you change too, considering it makes the same predictions for the next 3 gw.

**Comment by nbarlowATI** [comment]
@Hughesy this is a good point - it's only the Transactions table that depends on the FPL_TEAM_ID and this is a very small and quick table to fill - it would be good if we can add an option to have multiple squads in there and then use the team_id as an argument, and pick the correct squad, without having to refill all the other tables.
We should definitely try to add this as a feature.
