### ISSUE TITLE
Programmatically apply recommended transfers

### ISSUE THREAD

**Issue by RajeshTailor1** [alan-turing-institute/AIrsenal#286]
Not exactly an issue more of a feature request :)

Is there a way to pass a switch to the optimisation routine to accept the recommended transfer so it uses the fpl account details and executes it directly?

**Comment by jack89roberts** [comment]
Thanks for the suggestion. This reddit post suggests it should be possible: https://www.reddit.com/r/FantasyPL/comments/b4d6gv/fantasy_api_for_transfers/

Probably would involve adding a function to the `FPLDataFetcher` class to do this, and then optionally calling that from the optimisation code. Or maybe have a separate `airsenal_make_transfers` script to make it less likely that transfers are made by accident!

**Comment by nbarlowATI** [comment]
This would be great!!  Another step towards a fully robotic player :)
I think it shouldn't be too difficult either, since the TransferSuggestions from the optimization are stored in the database.  
I agree with @jack89roberts though that having a separate script to avoid accidental transfers is a good idea!

**Comment by RajeshTailor1** [comment]
It’s great to hear this is possible and I agree a separate script to avoid accidental transfers.  I don’t mind taking a look at this but won’t be likely for at least 2-3 weeks.
