### ISSUE TITLE
Prediction: Can we cache the compiled models?

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/AIrsenal#292]
When starting the prediction we see something like:
```
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_8c4b3dae224ed40cd55af0e4da27a5f1 NOW.
```
which takes a bit of time. I think that's for the team model, presumably the same happens for the player model (but gets swamped by other print statements).

I may be wrong but I think this relates just to compiling the stan code, not fitting the model. Maybe we could look into compiling the models the first time AIrsenal is run, and then use the cached ones after for a small speed improvement.

**Comment by anguswilliams91** [comment]
This will be the player model, not the team model (that one is compiled and pickled when `bpl` is installed because fitting it tends to take significantly less time than compiling it). You could apply the same trick here to compile the player model on install and this overhead would be removed (although I remember at the time thinking this wouldn't save much time overall so didn't bother).

**Comment by jack89roberts** [comment]
Done in #293 . I think you're right that it doesn't save much time, it's actually fitting the team model at the beginning which takes a little bit of time before things seem to start. I assumed it was the compilation because we had nothing printed to screen between compiling the player model and starting to get the player data (and turns out fitting the team model happens between those steps).
