### ISSUE TITLE
Add option to specify when chips are played

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/AIrsenal#314]
We can add the `--allow_wildcard`, `--allow_free_hit`, `--allow_bench_boost` or `--allow_triple_captain` flags to the optimisation to include the possibility of playing chips as part of the transfer strategy (in any of the gameweeks being optimised). This results in a lot of possible strategies so the optimisation takes a lot longer to run.

As an option, it would be nice if we could say "I want to play a wildcard in gameweek x", and then only compute strategies that play wildcards in gameweek x.

**Comment by nbarlowATI** [comment]
Good idea!!
In terms of the user-interface to this (and how we implement it in `fill_transfersuggestion_table.py`), how about, rather than adding more arguments on top of the current `--allow_wildcard` etc., we replace those with e.g. `--wildcard_week`, and have default value of -1 (no wildcard), then the user can specify the gameweek, or 0 for "any gameweek" (i.e. equivalent to current `--allow_wildcard`)?

**Comment by jack89roberts** [comment]
Do I remember you saying you'd started thinking about this one @nbarlowATI ? If not I might try to have a look at it before the hack session next week.

**Comment by nbarlowATI** [comment]
Hi @jack89roberts yep, I got some way towards this, and yesterday did a bit of merging what I had with the tree trimming you did... It's not finished, but what I have so far is in the `feature/314-choose-chip-week` branch...

**Comment by jack89roberts** [comment]
Nice, I'll pick out something else when I next play with AIrsenal in that case.

**Comment by subash774** [comment]
Hi,
I can't seem to find the flag/arg to trigger specifying of when the chips are played, do i need to modify ```airsenal_run_pipeline.py``` file?

**Comment by jack89roberts** [comment]
Hi @subash774 , they're available in `airsenal_run_optimization` (this is the last thing that `airsenal_run_pipeline` runs), specifically these arguments:

```
  --wildcard_week WILDCARD_WEEK
                        play wildcard in the specified week. Choose 0 for 'any week'.
  --free_hit_week FREE_HIT_WEEK
                        play free hit in the specified week. Choose 0 for 'any week'.
  --triple_captain_week TRIPLE_CAPTAIN_WEEK
                        play triple captain in the specified week. Choose 0 for 'any week'.
  --bench_boost_week BENCH_BOOST_WEEK
                        play bench_boost in the specified week. Choose 0 for 'any week'.
```

So `airsenal_run_optimization --wildcard_week 0` would consider playing a wildcard in any gameweek, and `airsenal_run_optimization --wildcard_week 5` would play a wildcard in gameweek  5, for example.

These options are not available in `airsenal_run_pipeline` at the moment, you're right. A contribution to add them to `airsenal_run_pipeline.py` would be very welcome!

**Comment by nbarlowATI** [comment]
Hi @subash774 , you're right, those options aren't currently exposed when running the full pipeline via `airsenal_run_pipeline` - I think this is just an oversight since the pipeline script is relatively new.  
So the options are:
* Run the optimization standalone (there's no problem doing this even after you run the full pipeline - each optimization run is independent):
```
airsenal_run_optimization --help
```
shows the options - the relevant ones are `wildcard_week`, `free_hit_week`, `triple_captain_week`, and `bench_boost_week`.    For any of these, provide an integer, that is either the gameweek that you'd like to play that chip, or `0` if you'd like the optimization to try all possible weeks (within the range you're optimizing over).  So to play wildcard next week, you'd do
```
airsenal_run_optimization --wildcard_week 5 
```
Or to include wildcard in the set of possibilities to be considered for all of the next 5 gameweeks, you'd do
```
airsenal_run_optimization --wildcard_week 0 --weeks_ahead 5
``` 

* The other thing that could be done is, as you say, to add those command line arguments from `fill_transfersuggestion_table.py` into `airsenal_run_pipeline.py` (note that the latter uses "click" while the former uses "argparse"), and pass them through the `run_optimize_squad` function into the call to `run_optimization`, having consolidated into a dict as is done in `fill_transfersuggestion.py`, i.e. 
```
    chip_gameweeks = {
        "wildcard": args.wildcard_week,
        "free_hit": args.free_hit_week,
        "triple_captain": args.triple_captain_week,
        "bench_boost": args.bench_boost_week,
    }
```

We will add this to the list of features/fixes to be implemented when we have time, but in the meantime if you'd like to have a go at it, Pull Requests are always welcome! :)

**Comment by nbarlowATI** [comment]
@jack89roberts  snap! :)  (you're obviously faster at typing than me!)

**Comment by subash774** [comment]
Thanks both! Will get to this when I get some time :)

**Comment by subash774** [comment]
@jack89roberts @nbarlowATI This has  been solved in [PR 422](https://github.com/alan-turing-institute/AIrsenal/pull/422). Please review
