### ISSUE TITLE
Trying to update team for this week, but keep getting the error below when running 3 week prediction

### ISSUE THREAD

**Issue by Hughesy** [alan-turing-institute/AIrsenal#320]
As above. 

I'm not quite sure what causing the issue as i've never had it before. 

Can you advise?

<img width="1214" alt="Screenshot 2020-12-04 at 10 47 40" src="https://user-images.githubusercontent.com/2457878/101155090-8f897080-361e-11eb-83ed-d5ea937b43c4.png">

**Comment by nbarlowATI** [comment]
Hi @Hughesy  I'm not sure what this might be, unless you've updated/changed your OSX version or XCode recently, but you could try getting gcc from homebrew and forcing the compilation to use that version... 
I also had some clang troubles recently and did 
```
brew install gcc@10
export CC=gcc-10
export CXX=g++-10
```
and was then able to compile the Stan model again.

**Comment by Hughesy** [comment]
> Hi @Hughesy  I'm not sure what this might be, unless you've updated/changed your OSX version or XCode recently, but you could try getting gcc from homebrew and forcing the compilation to use that version... 
> 
> I also had some clang troubles recently and did 
> 
> ```
> 
> brew install gcc@10
> 
> export CC=gcc-10
> 
> export CXX=g++-10
> 
> ```
> 
> and was then able to compile the Stan model again.

Yeah I recently update to the new OSX, never had trouble before that!

Will give it a go, thanks!

**Comment by Hughesy** [comment]
Did you ever find a fix for this? I need to do the above recommend every time I run a prediction @nbarlowATI

**Comment by nbarlowATI** [comment]
Hi @Hughesy ,  I'm not sure if anything has changed recently with xcode/clang or pystan that would make them work nicely again.    I'm also still setting the CC and CXX environment variables to point to the homebrew gcc every time I run predictions.

Depending on what else you want to compile on your machine, you could avoid having to type those commands every time by putting those lines that set the environment variables in your `.bash_profile`, or aliasing `gcc` to `gcc-10` and `g++` to `g++-10`.

(Also, it is possible that in the future (see #313) we will use numpyro rather than Stan for the probabilistic model, which might make compilation a bit easier! 🤞 )
