### ISSUE TITLE
Unpredictable behavior after using Free Hit

### ISSUE THREAD

**Issue by kaushalvivek** [alan-turing-institute/AIrsenal#331]
After using Free Hit in a particular GW, running the pipeline for the following GWs suggests changes based on the team used for the Free Hit GW, instead of the original team.

**Comment by jack89roberts** [comment]
Thanks @kaushalvivek . Just to check, is this from a recent installation of AIrsenal on the master branch, or an older installation/on the development branch? There have been quite a few changes to the optimization recently. I thought this was fixed on the current master but maybe not.

**Comment by kaushalvivek** [comment]
@jack89roberts  -- my bad, was using an old pull of the _develop_ branch. Running the pipeline right now on the latest pull of master. Should work, will update this comment.

**Comment by jack89roberts** [comment]
Actually, you probably will need to reinstall from the latest develop branch rather than master so you get the fix from https://github.com/alan-turing-institute/AIrsenal/pull/312 , sorry! Note that to use a free hit the argument to the optimization is now `--free_hit_week 0`, where 0 means to try a free hit in any gameweek, or you can replace that with the gameweek you want to play the free hit in.

**Comment by kaushalvivek** [comment]
@jack89roberts  -- you were right, a reinstall on the dev branch fixed this. I apologize for the delay in this update, got caught up with other stuff. Also noticed a massive performance improvement! The pipeline used to take roughly an hour to execute on an 8 core 8th gen i7 system -- down to 10 min!

**Comment by jack89roberts** [comment]
Thanks for the update, yes there's been a few big speed improvements since the start of the season 🙂
