### ISSUE TITLE
Need to include pygmo in requirements.txt?

### ISSUE THREAD

**Issue by sam-payne** [alan-turing-institute/AIrsenal#375]
When running AIrsenal on a built docker image, I encountered a 'module not found' error for pygmo. Placing this in requirements.txt and rebuilding fixed this.

**Comment by jack89roberts** [comment]
Thanks @sam-payne , I'll check the Docker config and update this. `pygmo` can only be installed with `pip` on Linux (otherwise you need to use `conda`) so we have it as an optional dependency at the moment.

When did you get the error, out of interest? It should only use pygmo if you ran `airsenal_make_squad --algorithm genetic`, if you got it without that then that's a bug we should fix too.

**Comment by sam-payne** [comment]
@jack89roberts I received this error when running `airsenal_make_squad --num_gw 3`. This was when running from a docker container having pulled from the repo yesterday.

**Comment by jack89roberts** [comment]
Ah ok, the docker build might need updating in general - I'll try to take a look soon. Is what you have is working now, though?

**Comment by sam-payne** [comment]
Yep, it is now working. I was also able to checkout and pull the dev branch within the docker image and rebuild with success.

**Comment by jack89roberts** [comment]
Great! The Docker's not working for me though 😄

**Comment by sam-payne** [comment]
I also needed to add a line to the Dockerfile to install Git before the main build.
