### ISSUE TITLE
Apple M1 Processor - Illegal hardware instruction on airsenal_run_prediction

### ISSUE THREAD

**Issue by dcracan** [alan-turing-institute/AIrsenal#405]
Hi,

I have an Apple Silicon M1 processor and I get the following error message on running airsenal_run_prediction:

_illegal hardware instruction  airsenal_run_prediction --weeks_ahead 3_

This doesn't really tell me where it fails, I suppose there's a library that is not supported on M1.

**Comment by nbarlowATI** [comment]
Hi @dcracan , oh, this is bad news, we were hoping that by migrating away from (py)stan we would improve compatibility in the latest version.

Since the error is occurring during prediction, it is overwhelmingly likely that the problem is somewhere in numpyro or jax.   There is this thread https://github.com/google/jax/issues/5501. talking about building jaxlib for M1, and somewhere about halfway down someone mentions the "illegal hardware instruction" message, so potentially something in that thread could be helpful?
(Unfortunately we don't have any M1 Macs to help debug! :) )

**Comment by dcracan** [comment]
Thank you for your quick reply! I will definitely have a look, and will report back. I could happily provide my time and my MacBook to debug this issue!

**Comment by JPKFin** [comment]
FWIW, I was able to build (and run) AIrsenal successfully on M1 silicon by using the Miniforge 3 (Apple Silicon) Python 3.9 package from here:
https://github.com/conda-forge/miniforge#miniforge3

**Comment by jack89roberts** [comment]
Is this now a non-issue @nbarlowATI but is there still some M1-specific setup needed?
