### ISSUE TITLE
Player on loan not recommended to transfer out

### ISSUE THREAD

**Issue by mildfuzz** [alan-turing-institute/AIrsenal#420]
Andi Zeqiri is out on a season long loan, but AIresenal is not recommending transferring him at least within the next three gameweeks. This seems like a bug?

**Comment by mildfuzz** [comment]
It also has Emiliano Martínez selected to my first team, who is out for quarantine, despite my sub keeper being available to play

**Comment by nbarlowATI** [comment]
Hi @mildfuzz , I think this is not necessarily a bug...  I just ran the predictions and confirmed that he is predicted zero points, so that part is working ok.     (For reference, once the db table is filled, can do:
```
python
>>> from airsenal.framework.utils import *
>>> p = get_player("Andi Zeqiri")
>>> tag = get_latest_prediction_tag()
>>> get_predicted_points_for_player(p, tag)
```
The optimization is harder to check.   It should be doing an exhaustive search of combinations of 0,1,2 transfers per week, that maximize the total points over the `num_weeks_ahead` specified.   It is possible that the best path it found just keeps him on the bench, and switches in or out some higher scoring players that would make more difference.   
We do have some tests for the optimization, to try and check that it's doing the right thing, but these are all based on slightly contrived situations.   So I wouldn't 100% rule out a bug, but haven't seen conclusive evidence that there is one either...

**Comment by nbarlowATI** [comment]
Ah, the Martinez one does sound more problematic :(    Did you run the predictions today?    From the run that I just did, Martinez is predicted 0 points for gw4, but is predicted to score in gw5 and 6 (which is based on the text "Expected back 18 Sep" from his status in the FPL API).

**Comment by mildfuzz** [comment]
Yeah, for now I have just manually ignored that bit, but does seem like an issue.

Also, when you said expected to score, I immediately thought you meant "score a goal", which would be unusual for a Goalie 😂

**Comment by nbarlowATI** [comment]
haha you heard it here first! 😂😂😂

**Comment by mildfuzz** [comment]
maybe I'll captain him next week
