### ISSUE TITLE
re-running optimization returns different team selection each time

### ISSUE THREAD

**Issue by niall-anthony-mcnulty** [alan-turing-institute/AIrsenal#426]
Hello. I noticed if I run the optimization twice, the team selection is different? Why is that? Is there a way to toggle between all of the team selections they run without having to run the optimization again and again (so I can choose which I think is best)? Cheers.

**Comment by nbarlowATI** [comment]
Hi @niall-anthony-mcnulty   hmm.... it's not expected behaviour that the optimization returns different results - it's supposed to do an exhaustive search of all possible combinations of 0, 1 or 2 transfers each gameweek and give a deterministic result...
Unless:
* you ran it on different days, in which case the prices might change such that some strategies are no longer possible (or become possible)
* you're doing a wildcard or free hit on one of the weeks,  in which case that team selection is a stochastic process.
* you're using a different version of the code between the two optimizations (and also reran predictions - recent changes to the code might have changed predicted scores for players slightly).

Do any of these situations apply?   If not, would it be OK if you post your team ID here, we can try to debug it...

**Comment by chahak13** [comment]
I can confirm the existence of this issue. My ID is 8326091. It's a bare-bones team that I use mainly while working on AIrsenal. I was running the same code multiple times with the default arguments and got different teams.
