### ISSUE TITLE
Optimisation only suggests single transfer even when using --num_free_transfers=2

### ISSUE THREAD

**Issue by mildfuzz** [alan-turing-institute/AIrsenal#463]
I have had a roll over transfer for weeks and the system never seems to elect to use it, makes me think it's not working

```
docker run -it --rm -v airsenal_data:/tmp/ -e "FPL_TEAM_ID=4891218" airsenal airsenal_run_optimization --weeks_ahead 3 --num_free_transfers=2
```

**Comment by jack89roberts** [comment]
Hmm we did fix a few things related to number of free transfers, but that was back in the summer (also if you're explicitly setting the num_free_transfers argument it shouldn't be a problem).

What number gets printed out if you do this?
```
docker run -it --rm -v airsenal_data:/tmp/ -e "FPL_TEAM_ID=4891218" airsenal python -c "from airsenal.framework.utils import get_free_transfers; print(get_free_transfers())"
```

If it's 1 rather than 2, maybe try pulling the latest version of the repo, rebuild the docker image, and see if it changes.

Does this mean you found a way to get the docker working again, by the way (#460)?

**Comment by mildfuzz** [comment]
Re: #460, no, this is the original system, the new system is still borked.

Thay does indeed return 2 :/

**Comment by jack89roberts** [comment]
In that case it should be ok I think (but you could still try updating the version you're running if you haven't for a while). Another check is that if it is working correctly the optimal strategy should always make at least 1 transfer in every gameweek (as when you have 2 free transfers you waste a transfer by not doing anything).

**Comment by mildfuzz** [comment]
I update every time I run it. Force of habit
