### ISSUE TITLE
Error on initial airsenal_run_pipeline in Docker environment

### ISSUE THREAD

**Issue by ssmichae** [alan-turing-institute/AIrsenal#479]
Built docker image using: docker build -t airsenal .
Then ran container using: docker run -it --rm -v airsenal_data:/tmp/ -e "FPL_TEAM_ID=xxxxxx" airsenal airsenal_run_pipeline

![image](https://user-images.githubusercontent.com/32813152/158713903-7a5b2db1-f87e-4ac5-985a-8a0c608d36fa.png)

**Comment by jack89roberts** [comment]
Thanks for reporting this @ssmichae . I think it was caused by a breaking change in the dateparser / regex libraries (https://github.com/scrapinghub/dateparser/pull/1046) - I've changed the AIrsenal dependencies to fix it. If you pull the latest version of airsenal and rebuild the container it should work now hopefully (you can also try `airsenal_run_pipeline --clean` if there are still issues).
