### ISSUE TITLE
Historic loan data

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/AIrsenal#521]
The injury, suspension, and other absence data we've scraped from TransferMarkt doesn't cover the case where someone is unavailable due to being sent on loan to another league.

**Comment by rchan26** [comment]
Having a look at this issue, but `pd.read_html` doesn't work for the transfer pages on TransferMarkt because the table isn't using the html table element. On the [pandas documentation](https://pandas.pydata.org/docs/reference/api/pandas.read_html.html), it says:

```This function searches for <table> elements and only for <tr> and <th> rows and <td> elements within each <tr> or <th> element in the table. <td> stands for “table data”. This function attempts to properly handle colspan and rowspan attributes. If the function has a <thead> argument, it is used to construct the header, otherwise the function attempts to find the header within the body (by putting rows with only <th> elements into the header).```

For transfer pages, for some reason, tables are just built using `<div>` tags (e.g. look at source code for [Kyle Walker](https://www.transfermarkt.co.uk/kyle-walker/transfers/spieler/95424)). Any tips to deal with these?
