### ISSUE TITLE
CF - Captcha block

### ISSUE THREAD

**Issue by pentatonicfunk** [alan-turing-institute/AIrsenal#523]
```
Error loging in: b'<html><head><title>premierleague.com</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">Please enable JS and disable any ad blocker</p><script data-cfasync="false">var dd={\'cid\':\'AHrlqAAAAAMAyEW3uBoxkWsAiztmHA==\',\'hsh\':\'5DE3E6A7D87D0E4E8979F7A1C7BD73\',\'t\':\'fe\',\'r\':\'b\',\'s\':37449,\'e\':\'fcb087d9b684a6f9f2f203e39e4e93d166ef40a03954624b7a91b726fba4ebb9\',\'host\':\'geo.captcha-delivery.com\'}</script><script data-cfasync="false" src="https://ct.captcha-delivery.com/c.js"></script></body></html>\n'
```
i guess is more like my IP rather than the airsenal responsibility ?

**Comment by nbarlowATI** [comment]
Hi @pentatonicfunk !  Hmm.... interesting, I haven't seen this before... 
Do you ever get a Captcha if you login to the FPL website normally?   I've never seen one, but maybe they do add them for some IPs..... ?  That's pretty annoying if so...

You should hopefully still be able to run the AIrsenal pipeline, falling back on transactions in your database rather than from the API, if you remove your FPL_LOGIN and FPL_PASSWORD from the AIRSENAL_HOME directory (that you can find by doing `airsenal_env_get` ), and then if prompted, say "n" to logging in to the FPL API...   
This way, the optimization won't have access to the exact player sell values from your squad (as it only knows which week you bought or sold a player, while the prices can vary every day), but should hopefully still be accurate enough.

**Comment by pentatonicfunk** [comment]
> Do you ever get a Captcha if you login to the FPL website normally?

not _normally_ but yea, sometimes i do, especially if im using my private VPN ( which is understandably due to the abuse history of my vpn server )

i got it working in the end, by turning of the VPN and use IP from my ISP directly.
And yea i dont think we can solve captcha programmatically ( + ethically )
closing this.
