### ISSUE TITLE
Scripts to dump DB contents to CSV / JSON

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/AIrsenal#63]
It was more painful than it should have been to get the 18/19 season data ready for the start of the 19/20 season.  
For next season we should have scripts ready that output the contents of the DB to the player_summary_YYYY.json,  player_detail_YYYY.json and results_YYYY_with_gw.csv files, in the expected formats.

**Comment by nbarlowATI** [comment]
Script should go in the `airsenal/scripts/` directory, and have an entrypoint defined in `setup.py`.
Tables to output are listed in `airsenal/framework/schema.py`.
No need to save "predictions" or "transfersuggestions".



Save to ```airsenal/data``` using the same format and naming convention as files that are already there.

**Comment by chiefsan** [comment]
I've written a script to dump the database - https://github.com/chiefsan/AIrsenal/blob/master/airsenal/scripts/dump_db_contents.py
I've also defined an entrypoint in `setup.py`

1) What is the role of `player_id` in the `Fixture` database?
2) Instead of storing multiple files for different seasons (teams_1516, teams_1617, etc.), is it okay if a single file is stored with the field season in it?

**Comment by nbarlowATI** [comment]
Hi @chiefsan 
this is great!! Many thanks for contributing! :)
To have a go at answering your questions:
1) Hmm good question - it is possible/likely that it isn't used at all - indeed from `scripts/fill_fixture_table.py` it doesn't seem that it's ever filled, and I can't find anywhere it's used... It's likely left over from some earlier bit of thinking.   In any case, none of the ForeignKey fields need to be dumped into files I don't think - they are all imported from other tables when we build the database.
2) Yep, that's totally fine, and probably a very good idea.  We should update the scripts that fill the database tables from file to reflect this though..

Could you submit a Pull Request for this?   We're possibly going to be doing quite a bit of development on the package in the next weeks as we're all locked down, so it would be good to get this in soon! :)

Thanks again!
Nick

**Comment by jack89roberts** [comment]
I think having `player_id` in the `Fixture` and `Result` tables are needed for the SQLAlchemy relationships/back propagation to work, e.g. so that each `Player` comes with an automatically populated list of his fixtures and results.

So I think `player_id` doesn't need to be in the database dump for those tables, but it does need to be in the schema and dealt with properly when creating the database (but maybe sqlalchemy will figure that out automatically anyway).
