### ISSUE TITLE
Will `airsenal_run_optimization` apply the transfers with the FPL API?

### ISSUE THREAD

**Issue by sam-cutter** [alan-turing-institute/AIrsenal#641]
When running `airsenal_run_optimization`, I am prompted to optionally enter my FPL login details. If I do enter these details, will the transfers be automatically applied to my team, or is this purely for the purpose of retrieving accurate player sell values? I am assuming that this command will simply provide me with the "printout", so-to-speak, of the recommended transfers, and that they will only be applied if I run `airsenal_make_transfers`. Thank you.

**Comment by jack89roberts** [comment]
Yes, the only commands that will apply changes to your team are `airsenal_make_transfers`, `airsenal_set_lineup`, or `airsenal_run_pipeline --make_transfers`. Logging in lets the optimisation run with the latest status of your team (e.g. to get exact sale prices or to get any transfers you made since the last gameweek deadline that aren't publicly visible yet).

**Comment by sam-cutter** [comment]
Ah, that makes sense. Thank you.
