### ISSUE TITLE
Google Login fails 

### ISSUE THREAD

**Issue by pedrovalenteferreira** [alan-turing-institute/AIrsenal#661]
Hi,

I'm trying to run "airsenal_set_lineup" with and without login and it always fails with the following error: HTTPError: Unable to access FPL API: 403 Client Error: Forbidden for url: https://fantasy.premierleague.com/api/my-team/1023607/

"airsenal_run_prediction --weeks_ahead 3" also doesn't take into account my team which I will assume that it's because of the above error.

I personally think that the reason for this is that my login on the FPL website is through Google. Am I correct? If so, is there any way to fix this?

**Comment by pedrovalenteferreira** [comment]
Hi  @nbarlowATI,

Thank you for your reply. I get the following error when running the `airsenal_run_optimization`:

> /home/et/miniconda3/envs/airsenalenv/lib/python3.12/site-packages/airsenal/framework/data_fetcher.py:144: UserWarning: Skipping login which means AIrsenal may have out of date information for your team.
>   warnings.warn(
> /home/et/miniconda3/envs/airsenalenv/lib/python3.12/site-packages/airsenal/framework/optimization_utils.py:132: UserWarning: Failed to get current squad from API:
> **Unable to access FPL API: 403 Client Error: Forbidden for url: https://fantasy.premierleague.com/api/my-team/1023607/
> Using DB instead, which may be out of date.**
>   warnings.warn(
> Getting starting squad for 1023607
> /home/et/miniconda3/envs/airsenalenv/lib/python3.12/site-packages/airsenal/framework/utils.py:431: UserWarning: Failed to get actual free transfers from a logged in API:
> Unable to access FPL API: 403 Client Error: Forbidden for url: https://fantasy.premierleague.com/api/my-team/1023607/
> Will try to estimate it from the API without logging in, which will not include any transfers used in the current gameweek.
>   warnings.warn(
> it/s/home/et/miniconda3/envs/airsenalenv/lib/python3.12/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.

**Comment by nbarlowATI** [comment]
Hi @pedrovalenteferreira,  so, I think all the messages here are "warnings" rather than "errors" - the ones related to the 403 status code for not being able to access the "my-team" url are expected when we are not logged in (perhaps we should add a `--no-login` command-line option so that it doesn't even try, and spares the user from seeing all these warnings...)

For the last message, the one about os.fork() is incompatible with multithreaded code, I can confirm that I also see this when I run with python 3.12 (but not with 3.10).   I wonder if it is related to a deprecation of "fork" in 3.12, which comes up in a stack overflow search.
For me though (on an M1 Mac) the optimization does go ahead as normal anyway though.   Is this not the case for you?   If not, what OS are you using, and what version of AIrsenal (can check the "version" in `pyproject.toml`)?

**Comment by pedrovalenteferreira** [comment]
Hi. So I was able to overcome the login issue by logging in on FPL website with Google Account and then changing the password to a new one. The changes were not immediate but after a week I've noticed that my login with Google was failing and after the with new password I was able to login. After this, login with Airsenal is now working correctly as expected.
