### ISSUE TITLE
24-25 Season

### ISSUE THREAD

**Issue by Iain-SF** [alan-turing-institute/AIrsenal#677]
Hi All,

I'm new to this so be kind... Apologies if this is not the correct Forum but cant find anywhere else.

I have been trying to get Airsenal working to learn a bit about Python, AI, ML etc but hitting a brick wall when trying to update db's for 24/25 season.
I have done the following:

Cloned repo
Created Docker and Conda env
Created DB's (I used chat GPT to help here and think I made some placeholder DB's - maybe the issue??)
When i go to update DB's I get an Error regarding Ipswich, IPS. 

Any help would be great.

Thanks

**Comment by jack89roberts** [comment]
Hi @Iain-SF , thanks for posting. The main branch doesn't have everything setup for the new season yet, but we have it mostly in place on the `develop` branch. You can either wait for that to be merged (should be this week hopefully) or otherwise install the develop version by doing:

```bash
git checkout develop
git pull
```

and then re-installing AIrsenal as per the readme (e.g. with `pip install --force-reinstall .` in your virtual environment, but if you're trying in docker then you should be able to just delete and re-create the container).

Let us know if you're still having problems after that 🙂

**Comment by Iain-SF** [comment]
Hi @jack89roberts,

Awesome! Appreciate your help. I'll hang fire for the merge, looking forward to getting started.

**Comment by jack89roberts** [comment]
It's merged now (so `git pull` then reinstalling etc. should work)

**Comment by Iain-SF** [comment]
Morning, ok great, thanks for letting me know.
